### ISSUE TITLE
Memory Exception when running python 3.7 on Windows 64-bit

### ISSUE THREAD

**Issue by blakeinate** [flababah/cpuid.py#10]
I have looked through the code and can not seem to find the cause of this bug.

`OSError: exception: access violation when writing 0x00000000XXXXXXXX`

The code runs fine on 3.7 in Ubuntu. 2.7 runs fine on Windows 64-bit. 
The offending line is:

`self.func_ptr(strust, eax, ecx)`

Any idea of a root cause?

**Comment by flababah** [comment]
That's odd. I just downloaded and tested on Python 3.7.0, both 32 bit and 64 bit. No problem with either here.

Maybe the difference is the version of Windows? Which version did you try? I'm on Windows 7, 64 bit.

**Comment by blakeinate** [comment]
I ran it on Windows 10 both a physical machine and a VM. I have not tried
it on any previous versions.

**Comment by blakeinate** [comment]
What resource are you using to determine the opcodes for different operating systems?

**Comment by flababah** [comment]
The problem should be fixed now. I had a brainfart in commit fac260a33 where I only moved the lower 32 bits of the address to the struct. I'm surprised it worked on Windows 7 64 bit. Seems like it ran it in an address space where only the lower 32 bits were needed.

About generating the opcodes... I just put the assembly in a text file and used the GNU assembler to assemble. Then you then can use `objdump -d` to disassemble the object file which shows the machine code hex.

| opcode.asm |
| ----------------|
|mov %rcx,%r9|

`as opcode.asm && objdump -d a.out`
```
a.out:     file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <.text>:
   0:   49 89 c9                mov    %rcx,%r9

```
