### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by irusanov** [flababah/cpuid.py#11]
Do you have a donation link?
I want to "send" you a beer or two, since your project helped me a bit.

Thanks!

**Comment by fpelliccioni** [comment]
Thank you!
I'm curious to know what you are doing with cpuid ...; P
It had not occurred to me to put a link for donations, you have given me a good idea.
What were you thinking? Crypto donation is ok for you? Or what?

**Comment by flababah** [comment]
Hi Ivan. Glad to hear you found it useful! I don't have a donation link, but I'll be happy to drink a beer with you if we ever cross paths in an airport. ;)

**Comment by irusanov** [comment]
I needed a python script to get the cpuid, so I can make some checks for supported CPU.
Python is not my strength and your script was very helpful.
Used it in a fork of old script for controlling AMD Ryzen P-States, now updated and with a gui: https://github.com/irusanov/ZenStates-Linux

If you ever add a donation link, I would be happy to donate you something (not much, just a part of what people have donated me).
