### ISSUE TITLE
How about calling cpuid with subleaf?

### ISSUE THREAD

**Issue by vxuyu** [flababah/cpuid.py#8]
I noticed that cpuid can be called with %eax as leaf, and %ecx as subleaf, e.g., when query Intel thread/core and cache topology using %eax=4 or %eax=Bh. [cpuid wiki](https://en.wikipedia.org/wiki/CPUID#EAX=4_and_EAX=Bh:_Intel_thread/core_and_cache_topology)

However, cpuid.py seems to only consider leaf, i.e., %eax, ignoring subleaf, i.e., %ecx.

**Comment by flababah** [comment]
I was not aware of that feature. Check the latest commit (fac260a) which adds the option of setting ECX/subleaf. I have verified that it shows different values depending on which CPU runs the script, but not that the values make sense. You are more than welcome to add some useful information to the example script. :)

**Comment by vxuyu** [comment]
Glad to see your update. I checkout the latest commit `fac260a `, and use it to test Intel RDT support on two different machine, and the result meets the reality.

Specifically, I test the CMT/MBM feature in Intel RDT, see chap. 17.17.4 & 17.17.5 of Intel® 64 and IA-32 Architectures Software Developer’s Manual Volume 3B: System Programming Guide, Part 2. Intel RDT in supported from some Broadwell and almost Skylake servers.  `cpuid.py` reports '--' on my Ivy Bridge server, and 'Yes' on my Broadwell server.

I have also submit a pull request.
